server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/county-mng-staff-db?createDatabaseIfNotExist=true
    username: root
    password: pool
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  application:
    name: STAFF-DETAILS-SERVICE